services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped
    env_file: .env
    environment:
      - DISCORD_TOKEN=
      - DB_NAME=cloud_db
      - DB_USER=admin_cloud
      - DB_PASS=admin
      - DB_PORT=5432
      - DB_HOST=db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=admin_cloud
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cloud_db
    ports:
      - 5432:5432
